### Obtener todos los autores
GET http://localhost:3000/api/autores

### Obtener un autor
GET http://localhost:3000/api/autores/1

### Obtener posts de un autor
GET http://localhost:3000/api/autores/1/posts

### Crear un autor
POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "Jose Perez",
    "email": "josee@gmail.com",
    "imagen": "https://placehold.co/400"
}

### Actualizar un autor
PUT http://localhost:3000/api/autores/1
Content-Type: application/json

{
    "nombre": "Marino Sanjurjo",
    "email": "marino@gmail.com",
    "imagen": "https://placehold.co/400"
}

### Eliminar un autor
DELETE http://localhost:3000/api/autores/6
